"""Generate Photoshop .jsx scripts that drop EDITABLE Khmer text layers onto a
cleaned page, using transcript.json (bubble positions) + a numbered Khmer list.

Usage:
    python -m manhwaprep.psgen <chapter_output_dir> [--font NAME] [--khmer FILE]

It reads <dir>/transcript.json and <dir>/khmer.txt (Claude's numbered Khmer),
and writes <dir>/photoshop/page_NNN.jsx. In Photoshop: open the cleaned page,
File > Scripts > Browse > page_NNN.jsx — a real text layer appears on each
bubble, fully editable.

Khmer shaping is done by Photoshop, so install a Khmer font and enable
Preferences > Type > "Middle Eastern and South Asian" (World-Ready) features.
"""

from __future__ import annotations

import argparse
import json
import os
import re

# macOS ships "Khmer Sangam MN"; this is its PostScript name.
DEFAULT_FONT = "KhmerSangamMN"

_JSX_HEADER = """#target photoshop
// Auto-generated by ManhwaPrep. Open the cleaned page first, then run this.
app.preferences.rulerUnits = Units.PIXELS;
var doc = app.activeDocument;
var FONT = "%(font)s";   // <- change to your Khmer font's PostScript name if needed

function _black() {
  var c = new SolidColor(); c.rgb.red = 0; c.rgb.green = 0; c.rgb.blue = 0; return c;
}
function addText(s, x, y, w, h, name) {
  var L = doc.artLayers.add();
  L.kind = LayerKind.TEXT;
  L.name = name;
  var t = L.textItem;
  t.kind = TextType.PARAGRAPHTEXT;
  t.position = [new UnitValue(x, "px"), new UnitValue(y, "px")];
  t.width = new UnitValue(Math.max(24, w), "px");
  t.height = new UnitValue(Math.max(24, h), "px");
  t.justification = Justification.CENTER;
  try { t.font = FONT; } catch (e) {}
  t.size = new UnitValue(Math.max(10, Math.round(h * 0.30)), "px");
  t.color = _black();
  t.contents = s;
}
"""


def parse_khmer_list(text: str) -> dict[int, str]:
    """Parse Claude's numbered output: '12. [bubble] ខ្មែរ' -> {12: 'ខ្មែរ'}."""
    out: dict[int, str] = {}
    for line in text.splitlines():
        m = re.match(r"\s*(\d+)\s*[.)\-]\s*(?:\[[^\]]*\]\s*)?(.*\S)?\s*$", line)
        if m and m.group(2):
            out[int(m.group(1))] = m.group(2).strip()
    return out


def _js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def generate(
    out_dir: str,
    khmer_map: dict[int, str],
    font: str = DEFAULT_FONT,
    kinds=("bubble", "sfx"),
) -> list[tuple[str, int]]:
    with open(os.path.join(out_dir, "transcript.json"), encoding="utf-8") as f:
        data = json.load(f)
    jdir = os.path.join(out_dir, "photoshop")
    os.makedirs(jdir, exist_ok=True)

    written = []
    for p in data["pages"]:
        lines = [_JSX_HEADER % {"font": font}]
        n = 0
        for it in p["items"]:
            if it["kind"] not in kinds:
                continue
            kh = khmer_map.get(it["n"])
            if not kh:
                continue
            x, y, w, h = it["bbox"]
            lines.append(
                f'addText("{_js_escape(kh)}", {x}, {y}, {w}, {h}, '
                f'"kh_{it["n"]}_{it["kind"]}");'
            )
            n += 1
        path = os.path.join(jdir, f"page_{p['page']:03d}.jsx")
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        written.append((path, n))
    return written


def main():
    ap = argparse.ArgumentParser(prog="manhwaprep.psgen")
    ap.add_argument("dir", help="chapter output dir (has transcript.json)")
    ap.add_argument("--khmer", help="numbered Khmer file (default: <dir>/khmer.txt)")
    ap.add_argument("--font", default=DEFAULT_FONT, help="Khmer font PostScript name")
    ap.add_argument(
        "--bubbles-only", action="store_true", help="skip [sfx], place dialogue only"
    )
    args = ap.parse_args()

    khmer_file = args.khmer or os.path.join(args.dir, "khmer.txt")
    with open(khmer_file, encoding="utf-8") as f:
        khmer_map = parse_khmer_list(f.read())
    if not khmer_map:
        raise SystemExit(f"No 'N. text' lines found in {khmer_file}")

    kinds = ("bubble",) if args.bubbles_only else ("bubble", "sfx")
    written = generate(args.dir, khmer_map, font=args.font, kinds=kinds)
    total = sum(n for _, n in written)
    print(f"Parsed {len(khmer_map)} Khmer lines. Wrote {len(written)} scripts, "
          f"{total} text layers total:")
    for path, n in written:
        print(f"  {os.path.basename(path)}  ({n} layers)")


if __name__ == "__main__":
    main()
